exports.AUTHENTICATED = "AUTHENTICATED"

exports.CLEAR_MESSAGE = "CLEAR_MESSAGE"

exports.LOADING_START = "LOADING_START"
exports.LOADING_END = "LOADING_END"

exports.LOGIN_SUCCESS = "LOGIN_SUCCESS"
exports.LOGIN_FAILED = "LOGIN_FAILED"

exports.SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
exports.SIGNUP_FAILED = "SIGNUP_FAILED"

exports.REGISTER_SUCCESS = "REGISTER_SUCCESS"
exports.REGISTER_FAILED = "REGISTER_FAILED"