exports.AUTHENTICATED = "AUTHENTICATED"

exports.CLEAR_MESSAGE = "CLEAR_MESSAGE"

exports.LOADING_START = "LOADING_START"
exports.LOADING_END = "LOADING_END"

exports.LOGIN_SUCCESS = "LOGIN_SUCCESS"
exports.LOGIN_FAILED = "LOGIN_FAILED"

exports.SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
exports.SIGNUP_FAILED = "SIGNUP_FAILED"

exports.REGISTER_SUCCESS = "REGISTER_SUCCESS"
exports.REGISTER_FAILED = "REGISTER_FAILED"

exports.GET_FIXED_VALUES = "GET_FIXED_VALUES"

exports.GET_BOOKS = "GET_BOOKS"

exports.ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS"
exports.ADD_BOOK_FAILED = "ADD_BOOK_FAILED"

exports.GET_SINGLE_BOOK = "GET_SINGLE_BOOK"

exports.UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS"
exports.UPDATE_BOOK_FAILED = "UPDATE_BOOK_FAILED"